name: .NET

on:
  push:
    branches: all
  pull_request:
    branches: all

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore Arche.sln
    - name: Build
      run: dotnet build Arche.sln --no-restore
    - name: Test
      run: dotnet test Arche.sln --no-build --verbosity normal
